name: Release(linux, windows)
on:
    workflow_call:
        inputs:
            release_tag:
                type: string
                description: "Tag to associate release with"
                required: true

env:
    SOURCE_DIR: ${{ github.workspace }}
    PROJECT_NAME: KPFB
    ARTIFACT_NAME: KPFB-${{inputs.release_tag}}

jobs:
    build:
        environment: CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Zip
              run: 7z a -tzip -mx5 -r0 ${{env.ARTIFACT_NAME}}.zip manifest.json src icons

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.ARTIFACT_NAME}}
                  path: ${{env.ARTIFACT_NAME}}.zip

    upload_release:
        environment: CI
        needs: [build]
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              id: artifacts
              with:
                  merge-multiple: true
                  path: ${{env.SOURCE_DIR}}/artifacts

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{inputs.release_tag}}
                  target_commitish: ${{github.sha}}
                  draft: true
                  files: ${{steps.artifacts.outputs.download-path}}/*
                  fail_on_unmatched_files: true
